#!/bin/sh
#
# This script updates a record in /vagrant/shared/machines pointing to the
# IP address assigned by VMware's DHCP server to our private network interface.
#
# This is necessary because we can't assign a static IP with the VMware
# provider.

set -eu

if [ "$IFACE" = "eth1" ]; then
    HOSTNAME=$(hostname --short)
    FQDN=${HOSTNAME}.kubernetes.local

    touch /vagrant/shared/machines
    sed -i -E "s/^[0-9x.]+( .*\b${HOSTNAME}\b)/${ADDR}\1/" \
        /vagrant/shared/machines
fi
